version: '3.2'

services:
  redis:
    image: redis
    container_name: redis-mq
    ports: 
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    entrypoint:
      redis-server --appendonly yes
    restart: always
  backend:
    container_name: slackbot_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - '.:/usr/src/app'
      - './usr/src/app/node_modules'
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis-mq

